name: PR Testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  handle-syncwith:
    if: github.event_name == 'pull_request'
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@2da5a86eec105fab2b298ef4ae56d01c34261793
    secrets: inherit

