name: Release and tag

on:
  push:
  pull_request:
    branches:
      - master
      - main

jobs:
  dump-env:
    name: Dump GitHub context
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    run: echo "$GITHUB_CONTEXT"
