name: Release and tag

on:
  push:
    branches:
      - master
      - main

jobs:
  detect-changes:
    runs-on: [ubuntu-latest]
    steps:
      - name: Detect change type
        shell: bash
        run: |
          ls
          echo ${{join(github.event.commits.*.message, ', ') }}
          echo "${{join(github.event.commits.*.message, ', ') }} | grep -i major > /dev/null && echo "RELEASE_TYPE=major" >> $GITHUB_ENV && exit 0
          echo "${{join(github.event.commits.*.message, ', ') }} | grep -i minor > /dev/null && echo "RELEASE_TYPE=minor" >> $GITHUB_ENV && exit 0
          echo "RELEASE_TYPE=patch" >> $GITHUB_ENV

