name: Experiment with tags

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  experiment-run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          fetch-depth: 0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Compute release number
        continue-on-error: true
        run: |
          git describe --tags --always # git describe fails if there are no tags yet
          retVal=$?
          if [ $retVal -ne 0 ]; then
            echo "No last tag detected, try to assign 0.0.0"
            tag="0.0.0"
            if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
              echo "tag $tag already exists, aborting"
              exit 1
            else
              echo "creating tag $tag"
              echo "VERSION=$tag" >> $GITHUB_ENV
              echo "VERSION=$tag"
            fi
            exit 0
          fi

          LATEST_TAG=`git describe --tags | cut -d'-' -f1 | tr -d v`
          echo "LATEST_TAG=$LATEST_TAG"
          MAJOR=`echo $LATEST_TAG | cut -d'.' -f1`
          MINOR=`echo $LATEST_TAG | cut -d'.' -f2`
          PATCH=`echo $LATEST_TAG | cut -d'.' -f3`

          case $RELEASE_TYPE in

            major)
              MAJOR=$((MAJOR+1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR+1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH+1))
              ;;
            *)
              echo "Unknown release type"
              exit 1
              ;;
          esac
          echo "VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
          echo "VERSION=$MAJOR.$MINOR.$PATCH"
      - name: Write version to file
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: '/.VERSION'
      - name: Commit VERSION file
        run : git add .VERSION
              git commit -m "update VER"
              git push origin HEAD
              git tag $VERSION master
