name: Release and tag

on:
  push:
    branches:
      - master
      - main

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@9a4bd2a3c763d32a96673b04f68e8320120d43dc
    secrets: inherit
