name: Release and tag
permissions:
  contents: write
on:
  pull_request:
    types: [opened, edited, closed] # we need this triggers for a title check

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@3084b29ac3d3be68802d95454793422cb16fae0c
    secrets: inherit
