name: Release and tag
permissions:
  contents: write
on:
  pull_request:
    types: [edited, closed]

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@9e7eb7eb0423aea0070435069304017b5ed34866
    secrets: inherit

