name: Release and tag
permissions:
  contents: write
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [edited]

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@c852f900099b1a128a1c38236aa7f63dbab30ba0
    secrets: inherit
