name: Release and tag
permissions:
  contents: write
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, edited] # we need this triggers for a title check

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@a90ae38a0a8bb6334ea68c6cebb511e03efe25ab
    secrets: inherit
