name: Release and tag

on:
  push:
    branches:
      - master
      - main

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@5377a009d39bd94d1afe230da0f402d3612b032a
    secrets: inherit
