name: Release and tag
permissions:
  contents: write
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, edited] # we need this triggers for a title check

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@87d264f7ef43e091c4b1b292691d97853e19f8f9
    secrets: inherit
