name: Release and tag

on:
  push:
    branches:
      - master
      - main

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@c30a5b8e302dd113eda7bc0abb9ff42faf66dbc8
    secrets: inherit

