name: PR Testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  handle-syncwith:
    if: github.event_name == 'pull_request'
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@f942e38036f30c0e6558c7ea10a9faae8da253bf
    with:
      release_type: 'minor'
    secrets: inherit
