name: Release and tag
permissions:
  contents: write
on:
  push:
    branches:
      - master
      - main
on:
  pull_request:
    types: [edited]

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@ef3d9dbbe53eed6763b44463fb57dac00bd3dcb8
    secrets: inherit
