name: Release and tag
permissions:
  contents: write
on:
  push:
    branches:
      - master
      - main

jobs:
  release-and-tag:
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@1da307946da539c7f654317c5d3dfb3313a6fb47
    secrets: inherit
