name: PR Testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  handle-syncwith:
    if: github.event_name == 'pull_request'
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@2643ba8aabf2e3c0707adc9e0c0432395a4571a1
    secrets: inherit

