name: PR Testing

on:
  push:
    branches:
      - master

jobs:
  handle-syncwith:
    if: github.event_name == 'pull_request'
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@5377a009d39bd94d1afe230da0f402d3612b032a
    secrets: inherit

