name: PR Testing

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  handle-syncwith:
    if: github.event_name == 'pull_request'
    name: Call reusable set version
    uses: NilFoundation/ci-cd/.github/workflows/reusable-set-version.yml@eff82bcd8cf49927a91e2c72e250820288ba5147
    with:
      release_type: 'minor'
    secrets: inherit

